
import java.util.LinkedHashSet;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author berkan
 */
public class RadioButtonVeComboBox extends javax.swing.JFrame {

    Set<String> diller = new LinkedHashSet<String>();
    
    /**
     * Creates new form RadioButtonVeComboBox
     */
    public RadioButtonVeComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        javaRadio = new javax.swing.JRadioButton();
        phytonRadio = new javax.swing.JRadioButton();
        phpRaido = new javax.swing.JRadioButton();
        DilGöster = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(javaRadio);
        javaRadio.setText("Java");

        buttonGroup1.add(phytonRadio);
        phytonRadio.setText("Phyton");
        phytonRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phytonRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(phpRaido);
        phpRaido.setText("Php");

        DilGöster.setText("Göster");
        DilGöster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DilGösterActionPerformed(evt);
            }
        });

        jLabel1.setText("ButtonGroup ekleyerek radio buttonun amacını yapmasını sağlıyoruz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DilGöster)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phytonRadio)
                                    .addComponent(javaRadio)
                                    .addComponent(phpRaido)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(javaRadio)
                .addGap(18, 18, 18)
                .addComponent(phytonRadio)
                .addGap(18, 18, 18)
                .addComponent(phpRaido)
                .addGap(38, 38, 38)
                .addComponent(DilGöster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phytonRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phytonRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phytonRadioActionPerformed

    public void goster(){
        
        String message = "Şu diller seçildi\n";
        
        for(String dil : diller){
            message +=dil + " ";
        }
        
        JOptionPane.showMessageDialog(this, message);
        
    }
    
    
    private void DilGösterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DilGösterActionPerformed
        if(javaRadio.isSelected()){
            
            diller.add("Java");           
            
        }
        else{
            
            diller.remove("Java");
        }
        
        
        if(phytonRadio.isSelected()){
            
            diller.add("Phyton");           
            
        }
        else{
            
            diller.remove("Phyton");
        }
        
        
        if(phpRaido.isSelected()){
            
            diller.add("Php");           
            
        }
        else{
            
            diller.remove("Php");
        }
        
        goster();
        
    }//GEN-LAST:event_DilGösterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonVeComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonVeComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DilGöster;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton javaRadio;
    private javax.swing.JRadioButton phpRaido;
    private javax.swing.JRadioButton phytonRadio;
    // End of variables declaration//GEN-END:variables
}
